"""Deterministic cross-domain target generator for Argus profiles."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

from .schema import PartnerProfile


def _canonical_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True) + "\n"


def _macro(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def _float(value: float) -> str:
    return f"{value:.6f}F"


@dataclass(frozen=True)
class CompilationArtifacts:
    profile_id: str
    files: Mapping[str, str]

    def write(self, output_dir: Path) -> tuple[Path, ...]:
        output_dir.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []
        for name in sorted(self.files):
            path = output_dir / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(self.files[name], encoding="utf-8", newline="\n")
            written.append(path)
        return tuple(written)


class ProfileCompiler:
    """Compile one validated profile into simulation, firmware, RTL, and test targets."""

    def compile(self, profile: PartnerProfile) -> CompilationArtifacts:
        return CompilationArtifacts(
            profile_id=profile.profile_id,
            files={
                "simulation_profile.json": self._simulation(profile),
                "firmware_profile.h": self._firmware_header(profile),
                "rtl_profile.vh": self._rtl_parameters(profile),
                "rtl_profile_defines.vh": self._rtl_defines(profile),
                "fault_test_vectors.json": self._test_vectors(profile),
            },
        )

    def _simulation(self, profile: PartnerProfile) -> str:
        payload = {
            "target": "simulation",
            "profile": profile.to_mapping(),
            "runtime": {
                "quality_gate": "confidence_coupled_safety_envelope",
                "unknown_intent_action": "safe_halt",
                "hardware_supervisor": "enabled",
            },
        }
        return _canonical_json(payload)

    def _firmware_header(self, profile: PartnerProfile) -> str:
        tag = _macro(profile.profile_id)
        actuator = profile.actuator
        expected_mnm = round(profile.actuator.max_torque_nm * 1000.0)
        expected_urad_s = round(profile.actuator.max_velocity_rad_s * 1000000.0)
        lines = [
            "/* Generated by argus.compiler. Reference artifact. */",
            f"#ifndef ATLAS_PROFILE_{tag}_H",
            f"#define ATLAS_PROFILE_{tag}_H",
            "",
            "#include <stdint.h>",
            "",
            "#define ATLAS_PROFILE_SCHEMA_MAJOR (1U)",
            f"#define ATLAS_PROFILE_SENSOR_COUNT ({len(profile.sensors)}U)",
            f"#define ATLAS_PROFILE_INTENT_COUNT ({len(profile.intent_classes)}U)",
            f"#define ATLAS_PROFILE_MAX_TORQUE_NM ({_float(actuator.max_torque_nm)})",
            f"#define ATLAS_PROFILE_MAX_VELOCITY_RAD_S ({_float(actuator.max_velocity_rad_s)})",
            f"#define ATLAS_PROFILE_MAX_TORQUE_MNM ({expected_mnm}L)",
            f"#define ATLAS_PROFILE_MAX_VELOCITY_URAD_S ({expected_urad_s}L)",
            "",
            "typedef struct",
            "{",
            "    float max_torque_nm;",
            "    float max_velocity_rad_s;",
            "    float position_min_rad;",
            "    float position_max_rad;",
            "} argus_actuator_limits_t;",
            "",
            "static const argus_actuator_limits_t argus_actuator_limits =",
            "{",
            f"    {_float(actuator.max_torque_nm)},",
            f"    {_float(actuator.max_velocity_rad_s)},",
            f"    {_float(actuator.position_min_rad)},",
            f"    {_float(actuator.position_max_rad)}",
            "};",
            "",
            f"#endif /* ATLAS_PROFILE_{tag}_H */",
            "",
        ]
        return "\n".join(lines)

    def _rtl_parameters(self, profile: PartnerProfile) -> str:
        tag = _macro(profile.profile_id)
        actuator = profile.actuator
        torque_mnm = round(actuator.max_torque_nm * 1000.0)
        velocity_urad_s = round(actuator.max_velocity_rad_s * 1_000_000.0)
        return "\n".join(
            [
                "// Generated by argus.compiler.",
                f"// Profile: {profile.profile_id}",
                f"localparam integer ATLAS_{tag}_SENSOR_COUNT = {len(profile.sensors)};",
                f"localparam integer ATLAS_{tag}_INTENT_COUNT = {len(profile.intent_classes)};",
                f"localparam integer ATLAS_{tag}_MAX_TORQUE_MNM = {torque_mnm};",
                f"localparam integer ATLAS_{tag}_MAX_VELOCITY_URAD_S = {velocity_urad_s};",
                "",
            ]
        )

    def _rtl_defines(self, profile: PartnerProfile) -> str:
        """Emit an include-safe limit header for FPGA target wrappers.

        ``rtl_profile.vh`` remains a module-local parameter artifact for source
        RTL probes. Target wrappers instead need preprocessor definitions before
        their module declarations, so this separate header prevents a generated
        profile from being confused with a source-level default.
        """

        tag = _macro(profile.profile_id)
        actuator = profile.actuator
        torque_mnm = round(actuator.max_torque_nm * 1000.0)
        velocity_urad_s = round(actuator.max_velocity_rad_s * 1_000_000.0)
        return "\n".join(
            [
                "// Generated by argus.compiler. Include once per FPGA build.",
                "`ifndef ATLAS_PROFILE_LIMITS_VH",
                "`define ATLAS_PROFILE_LIMITS_VH",
                "",
                f"`define ATLAS_PROFILE_ID_{tag} 1",
                f"`define ATLAS_PROFILE_SENSOR_COUNT {len(profile.sensors)}",
                f"`define ATLAS_PROFILE_INTENT_COUNT {len(profile.intent_classes)}",
                f"`define ATLAS_PROFILE_MAX_TORQUE_MNM {torque_mnm}",
                f"`define ATLAS_PROFILE_MAX_VELOCITY_URAD_S {velocity_urad_s}",
                "",
                "`endif // ATLAS_PROFILE_LIMITS_VH",
                "",
            ]
        )

    def _test_vectors(self, profile: PartnerProfile) -> str:
        vectors = [
            {
                "id": f"sensor_{path.sensor}_failure",
                "fault": {"sensor": path.sensor, "condition": "disconnect"},
                "expected_action": path.action,
            }
            for path in profile.fault_paths
        ]
        vectors.extend(
            [
                {
                    "id": "actuator_torque_over_limit",
                    "fault": {"actuator": profile.actuator.name, "torque_nm": profile.actuator.max_torque_nm + 1.0},
                    "expected_action": "safe_halt",
                },
                {
                    "id": "actuator_velocity_over_limit",
                    "fault": {
                        "actuator": profile.actuator.name,
                        "velocity_rad_s": profile.actuator.max_velocity_rad_s + 1.0,
                    },
                    "expected_action": "safe_halt",
                },
            ]
        )
        return _canonical_json({"profile_id": profile.profile_id, "vectors": vectors})
