"""Generate a hash-pinned requirements file for the Argus SDK runtime dependencies.

Resolves the dependency tree from the installed environment, fetches SHA-256
hashes from PyPI for each package version, and writes a requirements file
that pip can verify with --require-hashes.

Usage:
    python scripts/generate_hashed_requirements.py
"""

from __future__ import annotations

import json
import sys
import urllib.request
from importlib.metadata import distributions
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "requirements-hashed.txt"

# Runtime dependencies only - build tools and dev tools are not pinned here.
RUNTIME_DEPS = {
    "pynacl",
    "numpy",
    "scipy",
    "scikit-learn",
}

# Transitive runtime deps that must also be pinned.
TRANSITIVE_ALLOWLIST = {
    "cffi",          # PyNaCl
    "pycparser",     # cffi
    "joblib",        # scikit-learn
    "threadpoolctl", # scikit-learn
}


def fetch_hashes(package: str, version: str) -> list[str]:
    """Return all SHA-256 hashes for a package version from PyPI."""
    url = f"https://pypi.org/pypi/{package}/{version}/json"
    try:
        with urllib.request.urlopen(url, timeout=15) as response:
            data = json.loads(response.read())
        return [
            f["digests"]["sha256"]
            for f in data.get("urls", [])
            if f.get("digests", {}).get("sha256")
        ]
    except Exception as exc:
        print(f"WARNING: could not fetch hashes for {package}=={version}: {exc}", file=sys.stderr)
        return []


def collect_pinned() -> dict[str, str]:
    """Return {normalized_name: version} for all runtime and allowed transitive deps."""
    found: dict[str, str] = {}
    for dist in distributions():
        name = (dist.metadata["Name"] or "").lower().replace("_", "-")
        if name in RUNTIME_DEPS or name in TRANSITIVE_ALLOWLIST:
            found[name] = dist.version
    missing = RUNTIME_DEPS - set(found)
    if missing:
        raise RuntimeError(f"Missing runtime dependencies in environment: {sorted(missing)}")
    return found


def main() -> int:
    pinned = collect_pinned()
    lines = [
        "# Auto-generated by scripts/generate_hashed_requirements.py",
        "# Install with: pip install --require-hashes -r requirements-hashed.txt",
        "",
    ]
    failed = []
    for name in sorted(pinned):
        version = pinned[name]
        hashes = fetch_hashes(name, version)
        if not hashes:
            failed.append(f"{name}=={version}")
            continue
        lines.append(f"{name}=={version} \\")
        for h in hashes:
            lines.append(f"    --hash=sha256:{h} \\")
        lines[-1] = lines[-1].rstrip(" \\")
        lines.append("")

    if failed:
        print(f"ERROR: no hashes found for: {', '.join(failed)}", file=sys.stderr)
        return 1

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {OUTPUT}")
    print(f"Packages pinned: {len(pinned)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
